# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Product.destroy_all

Category.destroy_all

# 676.times do
#   Product.create(
#     title: Faker::Commerce.product_name,
#     price: Faker::Commerce.price,
#     stock_quantity: Faker::Number.number
#   )
# end
csv_file = Rails.root + 'db/products.csv'

# options = { file_encoding: 'iso-8859-1' } # Only needed if the CSV file was generated by Excel.

products = SmarterCSV.process(csv_file) # Pass the "options" hash as a second argument if CSV was created by Excel.

products.each do |product|
  # Product.create(
  #   category = Category.find_or_create_by(name: product.values[4]),
  #   title: product.values[0],
  #   description: product.values[1],
  #   price: product.values[2],
  #   stock_quantity: product.values[3],
  #   category: category
  # )
  category = Category.find_or_create_by(name: product[:category])

  new_prod = category.products.build(title: product[:name],
                                     description: product[:description],
                                     price: product[:price],
                                     stock_quantity: product[:stock_quantity])

  if new_prod.save
    puts 'success'
  else
    puts 'failure'
  end
end
